<?php

// This file was generated by running "composer dump-env prod"

return array (
  'APP_ENV' => 'prod',
  'APP_SECRET' => '94a41eb1235ad8f061651a6c7ded1ef4',
  'DATABASE_URL' => 'mysql://apiuser:apiuser@mariadb:3306/api?serverVersion=mariadb-10.4.19',
  'JWT_SECRET_KEY' => 'OGJjNjlmNzFmYWE0ZjVkZTE2ZDVkZjMw',
  'CORS_ALLOW_ORIGIN' => '^https?://(localhost|127\\.0\\.0\\.1)(:[0-9]+)?$',
);