<?php

// This file was generated by running "composer dump-env prod"

return array (
  'APP_ENV' => 'prod',
  'NzU5ZDUwYmNlMjA3Nzg2ZWU3NDE5YzA2' => '94a41eb1235ad8f061651a6c7ded1ef4',
  'DATABASE_URL' => 'mysql://apiuser:apiuser@mariadb:3306/api?serverVersion=mariadb-10.4.19',
  'JWT_SECRET_KEY' => 'MTBlNDY1ZDljNmEwYzNjN2I3NDhlOGMy',
  'CORS_ALLOW_ORIGIN' => '^https?://(localhost|127\\.0\\.0\\.1)(:[0-9]+)?$',
);